### ISSUE TITLE
Unknown Parameters

### ISSUE THREAD

**Issue by xlimit91** [Enichan/Ini#1]
What if i do not know the parameter names or the user decide to add a parameter?

For example:
[Excel Columns]
A=Col1
B=Col2

The user decide to add a column in the excel and write
C=Col3
into the ini file.

How i am able to get all parameters with a loop?

It would be nice if you could get all the parameters like this: (pseudo code)

for (int i=0; i < ini.Count; i++) {
   // i = the line of the ini. 0 is the value index, since a parameter have only one value its probably always 0.
   Console.WriteLine(ini[i][0].GetString(false, true));
}

**Comment by Enichan** [comment]
You can enumerate all parameters with a foreach loop, I just added some sample code to the bottom of the readme. Parameters are not guaranteed to be displayed in order though, so if you want that you'll probably want to use linq if you expect a section to have in order parameters, like so:

```csharp
foreach (var item in (from kvp in section orderby kvp.Key ascending select kvp)) {
    Console.WriteLine(item.Value.GetString(false, true));
}
```

This is an imperfect solution so I agree I should add an in order style as well.

**Comment by Enichan** [comment]
Implemented ordered ini sections and files. To load an ini file in order specify the ordered=true parameter when calling IniFile.Load. By doing this the order of the section using foreach will be preserved and the section can be indexed by integer. This means both loops below (foreach and for) are functionally equivalent.

```csharp
var ini = new IniFile();
ini.Load("somefile.ini", ordered: true);
var section = ini.First().Value;

var index = 0;
foreach (var item in section) {
    Console.WriteLine(string.Format("Item at index {0} is {1}", index, item.Value.GetString()));
    index++;
}

for (var i = 0; i < section.Count; i++) {
    Console.WriteLine(string.Format("Item at index {0} is {1}", i, section[i].GetString()));
}
```
