### ISSUE TITLE
“System.IO.FileNotFoundException”

### ISSUE THREAD

**Issue by weituotian** [Enichan/Ini#2]
“System.IO.FileNotFoundException”类型的未经处理的异常在 mscorlib.dll 中发生   其他信息: 未能找到文件“E:\c#\CSharpGrisaia1\Debug\config.ini”。

could not find config.ini

**Comment by Enichan** [comment]
This looks like your program cannot find the "config.ini" file, have you made sure it's in the folder?

**Comment by weituotian** [comment]
i want it to be created when the program run in the first time...

**Comment by Enichan** [comment]
You can do something like this:

```csharp
if (!File.Exists("config.ini")) {
    var ini = new IniFile();
    
    ini["main"]["value1"] = true;
    ini["main"]["value2"] = false;
    // etcetera
    
    ini.Save("config.ini");
}
```
